project:
  type: website

website:
  title: "Michael K. Gureghian"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: work.qmd
        text: Work Experience

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

